# Data Preparation and Cleaning

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
# Or set to a specific large number (from my df)
pd.set_option('display.max_columns', 1163)

## Data Source (Education)
- https://unehistoireduconflitpolitique.fr/telecharger.html
- https://www.insee.fr/fr/statistiques/8202319?sommaire=8202334

#### Skill Share
(According to the mail from Prof. Loumeau)

**Skill Share** measures the proportion of highly educated individuals (holding a *baccalauréat* or higher) within a municipality.

$$\text{Skill Share} = \frac{\text{Educated Residents}}{\text{Total Residents}}$$

* **Example:** If a town has 1,000 residents and 200 hold a degree $\rightarrow \text{Skill Share} = 0.20 \text{ (20\%)}$.

---

#### Delta Skill Share
**Delta Skill Share** captures the temporal change in this educated fraction immediately surrounding an election cycle.

$$\Delta\text{Skill Share} = \text{Skill Share}_{\text{After Election}} - \text{Skill Share}_{\text{Before Election}}$$

* **Positive Value ($+0.03$):** The proportion of highly educated residents grew post-election.
* **Negative Value ($-0.03$):** The proportion of highly educated residents shrank post-election.

In [3]:
# Load education dat
df_edu = pd.read_csv("diplomescommunes.csv", dtype={"codecommune": str})

# Standardise commune code to 5 characters (leading zeros)
df_edu["codecommune"] = df_edu["codecommune"].str.zfill(5)

C:\Users\tobia\AppData\Local\Temp\ipykernel_10808\2857989072.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_edu = pd.read_csv("diplomescommunes.csv", dtype={"codecommune": str})

In [4]:
df_edu.head(2)

,dep,nomdep,codecommune,nomcommune,nodiph1962,bach1962,suph1962,nodipf1962,bacf1962,supf1962,nodiph1968,bach1968,suph1968,nodipf1968,bacf1968,supf1968,nodip1968,bac1968,sup1968,nodiph1975,bach1975,suph1975,nodipf1975,bacf1975,supf1975,nodip1975,bac1975,sup1975,nodiph1982,bach1982,suph1982,nodipf1982,bacf1982,supf1982,nodip1982,bac1982,sup1982,nodiph1990,bach1990,suph1990,nodipf1990,bacf1990,supf1990,nodip1990,bac1990,sup1990,nodiph1999,bach1999,suph1999,nodipf1999,bacf1999,supf1999,nodip1999,bac1999,sup1999,nodiph2006,bach2006,suph2006,nodipf2006,bacf2006,supf2006,nodip2006,bac2006,sup2006,nodiph2011,bach2011,suph2011,nodipf2011,bacf2011,supf2011,nodip2011,bac2011,sup2011,nodiph2016,bach2016,suph2016,nodipf2016,bacf2016,supf2016,nodip2016,bac2016,sup2016,nodip1962,bac1962,sup1962,nodiph1960,nodiph1961,nodiph1963,nodiph1964,nodiph1965,nodiph1966,nodiph1967,nodiph1969,nodiph1970,nodiph1971,nodiph1972,nodiph1973,nodiph1974,nodiph1976,nodiph1977,nodiph1978,nodiph1979,nodiph1980,nodiph1981,nodiph1983,nodiph1984,nodiph1985,nodiph1986,nodiph1987,nodiph1988,nodiph1989,nodiph1991,nodiph1992,nodiph1993,nodiph1994,nodiph1995,nodiph1996,nodiph1997,nodiph1998,nodiph2000,nodiph2001,nodiph2002,nodiph2003,nodiph2004,nodiph2005,nodiph2007,nodiph2008,nodiph2009,nodiph2010,nodiph2012,nodiph2013,nodiph2014,nodiph2015,nodiph2017,nodiph2018,nodiph2019,nodiph2020,nodiph2021,nodiph2022,bach1960,bach1961,bach1963,bach1964,bach1965,bach1966,bach1967,bach1969,bach1970,bach1971,bach1972,bach1973,bach1974,bach1976,bach1977,bach1978,bach1979,bach1980,bach1981,bach1983,bach1984,bach1985,bach1986,bach1987,bach1988,bach1989,bach1991,bach1992,bach1993,bach1994,bach1995,bach1996,bach1997,bach1998,bach2000,bach2001,bach2002,bach2003,bach2004,bach2005,bach2007,bach2008,bach2009,bach2010,bach2012,bach2013,bach2014,bach2015,bach2017,bach2018,bach2019,bach2020,bach2021,bach2022,suph1960,suph1961,suph1963,suph1964,suph1965,suph1966,suph1967,suph1969,suph1970,suph1971,suph1972,suph1973,suph1974,suph1976,suph1977,suph1978,suph1979,suph1980,suph1981,suph1983,suph1984,suph1985,suph1986,suph1987,suph1988,suph1989,suph1991,suph1992,suph1993,suph1994,suph1995,suph1996,suph1997,suph1998,suph2000,suph2001,suph2002,suph2003,suph2004,suph2005,suph2007,suph2008,suph2009,suph2010,suph2012,suph2013,suph2014,suph2015,suph2017,suph2018,suph2019,suph2020,suph2021,suph2022,nodipf1960,nodipf1961,nodipf1963,nodipf1964,nodipf1965,nodipf1966,nodipf1967,nodipf1969,nodipf1970,nodipf1971,nodipf1972,nodipf1973,nodipf1974,nodipf1976,nodipf1977,nodipf1978,nodipf1979,nodipf1980,nodipf1981,nodipf1983,nodipf1984,nodipf1985,nodipf1986,nodipf1987,nodipf1988,nodipf1989,nodipf1991,nodipf1992,nodipf1993,nodipf1994,nodipf1995,nodipf1996,nodipf1997,nodipf1998,nodipf2000,nodipf2001,nodipf2002,nodipf2003,nodipf2004,nodipf2005,nodipf2007,nodipf2008,nodipf2009,nodipf2010,nodipf2012,nodipf2013,nodipf2014,nodipf2015,nodipf2017,nodipf2018,nodipf2019,nodipf2020,nodipf2021,nodipf2022,bacf1960,bacf1961,bacf1963,bacf1964,bacf1965,bacf1966,bacf1967,bacf1969,bacf1970,bacf1971,bacf1972,bacf1973,bacf1974,bacf1976,bacf1977,bacf1978,bacf1979,bacf1980,bacf1981,bacf1983,bacf1984,bacf1985,bacf1986,bacf1987,bacf1988,bacf1989,bacf1991,bacf1992,bacf1993,bacf1994,bacf1995,bacf1996,bacf1997,bacf1998,bacf2000,bacf2001,bacf2002,bacf2003,bacf2004,bacf2005,bacf2007,bacf2008,bacf2009,bacf2010,bacf2012,bacf2013,bacf2014,bacf2015,bacf2017,bacf2018,bacf2019,bacf2020,bacf2021,bacf2022,supf1960,supf1961,supf1963,supf1964,supf1965,supf1966,supf1967,supf1969,supf1970,supf1971,supf1972,supf1973,supf1974,supf1976,supf1977,supf1978,supf1979,supf1980,supf1981,supf1983,supf1984,supf1985,supf1986,supf1987,supf1988,supf1989,supf1991,supf1992,supf1993,supf1994,supf1995,supf1996,supf1997,supf1998,supf2000,supf2001,supf2002,supf2003,supf2004,supf2005,supf2007,supf2008,supf2009,supf2010,supf2012,supf2013,supf2014,supf2015,supf2017,supf2018,supf2019,supf2020,supf2021,supf2022,nodip1960,nodip1961,nodip1963,nodip1964,nodip1965,nodip1966,nodip1967,nodip1969,nodip1970,nodip1971,nodip1972,nodip1973,nodip1974,nodip1976,nodip1977,nodip1978,nodip1979,nodip1980,nodip1981,nodip1983,nodip1984,nodip1985,nodip1986,nodip1987,nodip1988,nodip1989,nodip1991,nodip1992,nodip1993,nodip1994,nodip1995,nodip1996,nodip1997,nodip1998,nodip2000,nodip2001,nodip2002,nodip2003,nodip2004,nodip2005,nodip2007,nodip2008,nodip2009,nodip2010,nodip2012,nodip2013,nodip2014,nodip2015,nodip2017,nodip2018,nodip2019,nodip2020,nodip2021,nodip2022,bac1960,bac1961,bac1963,bac1964,bac1965,bac1966,bac1967,bac1969,bac1970,bac1971,bac1972,bac1973,bac1974,bac1976,bac1977,bac1978,bac1979,bac1980,bac1981,bac1983,bac1984,bac1985,bac1986,bac1987,bac1988,bac1989,bac1991,bac1992,bac1993,bac1994,bac1995,bac1996,bac1997,bac1998,bac2000,bac2001,bac2002,bac2003,bac2004,bac2005,bac2007,bac2008,bac2009,bac2010,bac2012,bac2013,bac2014,bac2015,bac2017,bac2018,bac2019,bac2020,bac2021,bac2022,sup1960,sup1961,sup1963,sup1964,sup1965,sup1966,sup1967,sup1969,sup1970,sup1971,sup1972,sup1973,sup1974,sup1976,sup1977,sup1978,sup1979,sup1980,sup1981,sup1983,sup1984,sup1985,sup1986,sup1987,sup1988,sup1989,sup1991,sup1992,sup1993,sup1994,sup1995,sup1996,sup1997,sup1998,sup2000,sup2001,sup2002,sup2003,sup2004,sup2005,sup2007,sup2008,sup2009,sup2010,sup2012,sup2013,sup2014,sup2015,sup2017,sup2018,sup2019,sup2020,sup2021,sup2022,pbac1960,perbac1960,pbac1961,perbac1961,pbac1962,perbac1962,pbac1963,perbac1963,pbac1964,perbac1964,pbac1965,perbac1965,pbac1966,perbac1966,pbac1967,perbac1967,pbac1968,perbac1968,pbac1969,perbac1969,pbac1970,perbac1970,pbac1971,perbac1971,pbac1972,perbac1972,pbac1973,perbac1973,pbac1974,perbac1974,pbac1975,perbac1975,pbac1976,perbac1976,pbac1977,perbac1977,pbac1978,perbac1978,pbac1979,perbac1979,pbac1980,perbac1980,pbac1981,perbac1981,pbac1982,perbac1982,pbac1983,perbac1983,pbac1984,perbac1984,pbac1985,perbac1985,pbac1986,perbac1986,pbac1987,perbac1987,pbac1988,perbac1988,pbac1989,perbac1989,pbac1990,perbac1990,pbac1991,perbac1991,pbac1992,perbac1992,pbac1993,perbac1993,pbac1994,perbac1994,pbac1995,perbac1995,pbac1996,perbac1996,pbac1997,perbac1997,pbac1998,perbac1998,pbac1999,perbac1999,pbac2000,perbac2000,pbac2001,perbac2001,pbac2002,perbac2002,pbac2003,perbac2003,pbac2004,perbac2004,pbac2005,perbac2005,pbac2006,perbac2006,pbac2007,perbac2007,pbac2008,perbac2008,pbac2009,perbac2009,pbac2010,perbac2010,pbac2011,perbac2011,pbac2012,perbac2012,pbac2013,perbac2013,pbac2014,perbac2014,pbac2015,perbac2015,pbac2016,perbac2016,pbac2017,perbac2017,pbac2018,perbac2018,pbac2019,perbac2019,pbac2020,perbac2020,pbac2021,perbac2021,pbac2022,perbac2022,psup1960,persup1960,psup1961,persup1961,psup1962,persup1962,psup1963,persup1963,psup1964,persup1964,psup1965,persup1965,psup1966,persup1966,psup1967,persup1967,psup1968,persup1968,psup1969,persup1969,psup1970,persup1970,psup1971,persup1971,psup1972,persup1972,psup1973,persup1973,psup1974,persup1974,psup1975,persup1975,psup1976,persup1976,psup1977,persup1977,psup1978,persup1978,psup1979,persup1979,psup1980,persup1980,psup1981,persup1981,psup1982,persup1982,psup1983,persup1983,psup1984,persup1984,psup1985,persup1985,psup1986,persup1986,psup1987,persup1987,psup1988,persup1988,psup1989,persup1989,psup1990,persup1990,psup1991,persup1991,psup1992,persup1992,psup1993,persup1993,psup1994,persup1994,psup1995,persup1995,psup1996,persup1996,psup1997,persup1997,psup1998,persup1998,psup1999,persup1999,psup2000,persup2000,psup2001,persup2001,psup2002,persup2002,psup2003,persup2003,psup2004,persup2004,psup2005,persup2005,psup2006,persup2006,psup2007,persup2007,psup2008,persup2008,psup2009,persup2009,psup2010,persup2010,psup2011,persup2011,psup2012,persup2012,psup2013,persup2013,psup2014,persup2014,psup2015,persup2015,psup2016,persup2016,psup2017,persup2017,psup2018,persup2018,psup2019,persup2019,psup2020,persup2020,psup2021,persup2021,psup2022,persup2022,perbac1790,persup1790,perbac1791,persup1791,perbac1792,persup1792,perbac1793,persup1793,perbac1794,persup1794,perbac1795,persup1795,perbac1796,persup1796,perbac1797,persup1797,perbac1798,persup1798,perbac1799,persup1799,perbac1800,persup1800,perbac1801,persup1801,perbac1802,persup1802,perbac1803,persup1803,perbac1804,persup1804,perbac1805,persup1805,perbac1806,persup1806,perbac1807,persup1807,perbac1808,persup1808,perbac1809,persup1809,perbac1810,persup1810,perbac1811,persup1811,perbac1812,persup1812,perbac1813,persup1813,perbac1814,persup1814,perbac1815,persup1815,perbac1816,persup1816,perbac1817,persup1817,perbac1818,persup1818,perbac1819,persup1819,perbac1820,persup1820,perbac1821,persup1821,perbac1822,persup1822,perbac1823,persup1823,perbac1824,persup1824,perbac1825,persup1825,perbac1826,persup1826,perbac1827,persup1827,perbac1828,persup1828,perbac1829,persup1829,perbac1830,persup1830,perbac1831,persup1831,perbac1832,persup1832,perbac1833,persup1833,perbac1834,persup1834,perbac1835,persup1835,perbac1836,persup1836,perbac1837,persup1837,perbac1838,persup1838,perbac1839,persup1839,perbac1840,persup1840,perbac1841,persup1841,perbac1842,persup1842,perbac1843,persup1843,perbac1844,persup1844,perbac1845,persup1845,perbac1846,persup1846,perbac1847,persup1847,perbac1848,persup1848,perbac1849,persup1849,perbac1850,persup1850,perbac1851,persup1851,perbac1852,persup1852,perbac1853,persup1853,perbac1854,persup1854,perbac1855,persup1855,perbac1856,persup1856,perbac1857,persup1857,perbac1858,persup1858,perbac1859,persup1859,perbac1860,persup1860,perbac1861,persup1861,perbac1862,persup1862,perbac1863,persup1863,perbac1864,persup1864,perbac1865,persup1865,perbac1866,persup1866,perbac1867,persup1867,perbac1868,persup1868,perbac1869,persup1869,perbac1870,persup1870,perbac1871,persup1871,perbac1872,persup1872,perbac1873,persup1873,perbac1874,persup1874,perbac1875,persup1875,perbac1876,persup1876,perbac1877,persup1877,perbac1878,persup1878,perbac1879,persup1879,perbac1880,persup1880,perbac1881,persup1881,perbac1882,persup1882,perbac1883,persup1883,perbac1884,persup1884,perbac1885,persup1885,perbac1886,persup1886,perbac1887,persup1887,perbac1888,persup1888,perbac1889,persup1889,perbac1890,persup1890,perbac1891,persup1891,perbac1892,persup1892,perbac1893,persup1893,perbac1894,persup1894,perbac1895,persup1895,perbac1896,persup1896,perbac1897,persup1897,perbac1898,persup1898,perbac1899,persup1899,perbac1900,persup1900,perbac1901,persup1901,perbac1902,persup1902,perbac1903,persup1903,perbac1904,persup1904,perbac1905,persup1905,perbac1906,persup1906,perbac1907,persup1907,perbac1908,persup1908,perbac1909,persup1909,perbac1910,persup1910,perbac1911,persup1911,perbac1912,persup1912,perbac1913,persup1913,perbac1914,persup1914,perbac1915,persup1915,perbac1916,persup1916,perbac1917,persup1917,perbac1918,persup1918,perbac1919,persup1919,perbac1920,persup1920,perbac1921,persup1921,perbac1922,persup1922,perbac1923,persup1923,perbac1924,persup1924,perbac1925,persup1925,perbac1926,persup1926,perbac1927,persup1927,perbac1928,persup1928,perbac1929,persup1929,perbac1930,persup1930,perbac1931,persup1931,perbac1932,persup1932,perbac1933,persup1933,perbac1934,persup1934,perbac1935,persup1935,perbac1936,persup1936,perbac1937,persup1937,perbac1938,persup1938,perbac1939,persup1939,perbac1940,persup1940,perbac1941,persup1941,perbac1942,persup1942,perbac1943,persup1943,perbac1944,persup1944,perbac1945,persup1945,perbac1946,persup1946,perbac1947,persup1947,perbac1948,persup1948,perbac1949,persup1949,perbac1950,persup1950,perbac1951,persup1951,perbac1952,persup1952,perbac1953,persup1953,perbac1954,persup1954,perbac1955,persup1955,perbac1956,persup1956,perbac1957,persup1957,perbac1958,persup1958,perbac1959,persup1959
0,1,AIN,01001,ABERGEMENT-CLEMENCIAT,121.0,4.0,0.0,116.0,0.0,2.0,120.0,8.0,0.0,120.0,0.0,4.0,240.0,8.0,4.0,120.0,0.0,0.0,115.0,0.0,0.0,235.0,0.0,0.0,112.0,8.0,8.0,120.0,8.0,4.0,232.0,16.0,12.0,160.0,8.0,12.0,172.0,4.0,8.0,332.0,12.0,20.0,208.0,12.0,20.0,200.0,12.0,20.0,408.0,24.0,40.0,176.0,52.0,48.0,188.0,44.0,40.0,364.0,96.0,88.0,164.0,40.0,64.0,148.0,40.0,72.0,312.0,80.0,136.0,160.0,50.0,70.0,155.0,50.0,65.0,315.0,100.0,135.0,237.0,4.0,2.0,121,121,121.0,121.0,121.0,120.0,120.0,120.0,120.0,120.0,120.0,120.0,120.0,119.0,118.0,117.0,115.0,114.0,113.0,118.0,124.0,130.0,136.0,142.0,148.0,154.0,165.0,171.0,176.0,181.0,187.0,192.0,197.0,203.0,203.0,199.0,194.0,190.0,185.0,181.0,174.0,171.0,169.0,166.0,163.0,162.0,162.0,161.0,159,158,158,157,156,155,3,3,5.0,5.0,6.0,7.0,7.0,7.0,6.0,5.0,3.0,2.0,1.0,1.0,2.0,3.0,5.0,6.0,7.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,9.0,9.0,10.0,10.0,11.0,11.0,12.0,18.0,23.0,29.0,35.0,41.0,46.0,50.0,47.0,45.0,42.0,42.0,44.0,46.0,48.0,52,54,56,58,60,62,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0,5.0,6.0,7.0,9.0,9.0,10.0,10.0,11.0,11.0,12.0,13.0,14.0,15.0,16.0,16.0,17.0,18.0,19.0,24.0,28.0,32.0,36.0,40.0,44.0,51.0,54.0,58.0,61.0,65.0,66.0,68.0,69.0,71,72,74,75,76,77,115,115,117.0,117.0,118.0,119.0,119.0,119.0,119.0,118.0,117.0,116.0,116.0,116.0,116.0,117.0,118.0,119.0,119.0,127.0,133.0,140.0,146.0,153.0,159.0,166.0,175.0,178.0,181.0,184.0,188.0,191.0,194.0,197.0,198.0,197.0,195.0,193.0,191.0,190.0,180.0,172.0,164.0,156.0,149.0,151.0,152.0,154.0,156,158,159,161,162,163,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,3.0,5.0,6.0,7.0,8.0,7.0,7.0,6.0,6.0,5.0,5.0,5.0,6.0,7.0,8.0,8.0,9.0,10.0,11.0,17.0,21.0,26.0,30.0,35.0,39.0,43.0,42.0,42.0,41.0,42.0,44.0,46.0,48.0,52,54,56,58,60,62,1,2,2.0,3.0,3.0,3.0,4.0,3.0,3.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,2.0,3.0,3.0,5.0,5.0,6.0,6.0,7.0,7.0,8.0,9.0,11.0,12.0,13.0,15.0,16.0,17.0,19.0,23.0,26.0,29.0,31.0,34.0,37.0,46.0,53.0,59.0,66.0,71.0,69.0,68.0,66.0,64,62,61,59,58,57,236,237,238.0,238.0,239.0,239.0,240.0,239.0,239.0,238.0,237.0,236.0,236.0,235.0,234.0,234.0,233.0,233.0,232.0,245.0,257.0,270.0,282.0,295.0,307.0,320.0,340.0,349.0,357.0,366.0,374.0,383.0,391.0,400.0,402.0,395.0,389.0,383.0,377.0,370.0,354.0,343.0,333.0,322.0,313.0,313.0,314.0,314.0,316,316,317,317,318,319,3,3,5.0,5.0,6.0,7.0,7.0,7.0,6.0,5.0,3.0,2.0,1.0,2.0,5.0,7.0,9.0,11.0,14.0,16.0,15.0,15.0,14.0,14.0,13.0,13.0,13.0,15.0,16.0,17.0,19.0,20.0,21.0,23.0,34.0,45.0,55.0,65.0,75.0,86.0,93.0,90.0,86.0,83.0,84.0,88.0,92.0,96.0,104,108,112,116,120,124,1,2,2.0,3.0,3.0,3.0,4.0,3.0,3.0,2.0,2.0,1.0,1.0,2.0,3.0,5.0,7.0,9.0,10.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0,22.0,24.0,27.0,29.0,31.0,33.0,36.0,38.0,47.0,54.0,61.0,67.0,74.0,81.0,98.0,107.0,117.0,126.0,136.0,136.0,135.0,135.0,135,135,134,134,134,134,0.016667,0.263747,0.020661,0.265112,0.024691,0.273645,0.028571,0.275533,0.032520,0.276960,0.036290,0.276016,0.040161,0.281951,0.043825,0.279863,0.047619,0.281557,0.040161,0.203273,0.036290,0.155614,0.028571,0.097793,0.020661,0.053797,0.012552,0.034776,0.008403,0.029878,0.00,0.014553,0.016736,0.028915,0.033058,0.049344,0.04878,0.079893,0.064257,0.118608,0.079051,0.165024,0.093750,0.220910,0.107692,0.270285,0.105839,0.233246,0.101399,0.191132,0.100000,0.160530,0.096154,0.128430,0.095092,0.106413,0.091716,0.087936,0.090909,0.074475,0.087912,0.063262,0.093333,0.058517,0.100515,0.057499,0.107500,0.059491,0.111650,0.055663,0.117925,0.057858,0.121560,0.054095,0.127232,0.056168,0.132321,0.057563,0.135593,0.057665,0.167702,0.103220,0.200405,0.164281,0.229703,0.223157,0.256311,0.273044,0.283270,0.324336,0.310987,0.38740,0.335766,0.428618,0.350459,0.445253,0.364815,0.459423,0.378731,0.47399,0.393597,0.487630,0.409091,0.502685,0.412758,0.488606,0.417132,0.477593,0.419593,0.461203,0.423853,0.449700,0.427273,0.429812,0.430631,0.415525,0.434705,0.404729,0.436945,0.391071,0.440917,0.383374,0.444056,0.370707,0.447140,0.358389,0.004167,0.258736,0.008264,0.346656,0.008230,0.309675,0.008163,0.283460,0.012195,0.344722,0.012097,0.313533,0.012048,0.295427,0.015936,0.339420,0.015873,0.316527,0.012048,0.221407,0.012097,0.188429,0.008163,0.118989,0.008264,0.105912,0.004184,0.080759,0.004202,0.082646,0.000000,0.024269,0.008368,0.071814,0.012397,0.074068,0.020325,0.110082,0.028112,0.159038,0.035573,0.211192,0.039062,0.228504,0.046154,0.275212,0.047445,0.262141,0.048951,0.258610,0.050000,0.245155,0.051282,0.239243,0.052147,0.229759,0.053254,0.225855,0.053977,0.215801,0.054945,0.213452,0.058667,0.204161,0.061856,0.192131,0.067500,0.196561,0.070388,0.183970,0.073113,0.176159,0.075688,0.164513,0.080357,0.167941,0.082429,0.159146,0.084746,0.152992,0.097308,0.180054,0.109312,0.207342,0.120792,0.232488,0.130097,0.247915,0.140684,0.269616,0.150838,0.290923,0.160584,0.306260,0.179817,0.358725,0.198148,0.409002,0.218284,0.464208,0.237288,0.515142,0.257576,0.563235,0.255159,0.529312,0.253259,0.495426,0.249538,0.453424,0.247706,0.417109,0.245455,0.385826,0.243243,0.354205,0.241503,0.326816,0.238011,0.301127,0.236332,0.281792,0.234266,0.261884,0.232236,0.242073,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736,0.263747,0.258736

### Outcome Variable: Skill Share

| Column pattern | Meaning |
|---|---|
| `nodiph/f{year}` | Residents *without* any diploma (men/women) |
| `bach{year}/bacf{year}/bac{year}` | Residents with *baccalauréat* — high school level (men/women) |
| `suph{year}/supf{year}/sup{year}` | Residents with *university-level* education (men/women) |

**h** = hommes (men)

**f** = femmes (women)

**No info** = h + f = men + women

**Skill share** = (bach + sup) / (nodip + bach + sup), for men and women combined.  
**Delta skill share** = skill share *after* election − skill share *before* election.  
A negative value means the educated share *shrunk* post-election.

In [5]:
# educated = bach + suph + bacf + supf   # bac AND university

In [6]:
# Helper functions
def compute_skill_share(df, year):
    """Fraction of residents with bac or higher, for a given census year."""
    educated = (df[f"bach{year}"] + df[f"suph{year}"] +    # men: bac + university
                df[f"bacf{year}"] + df[f"supf{year}"])     # women: bac + university
    total    = (educated +
                df[f"nodiph{year}"] + df[f"nodipf{year}"]) # add no-diploma residents
    return educated / total                                 # share between 0 and 1

def compute_skill_share_trend(df, pre2_y, pre_y):
    """Change in skill share between two pre-treatment census years (pre-trend proxy)."""
    return compute_skill_share(df, pre_y) - compute_skill_share(df, pre2_y)

def compute_total_pop(df, year):
    """Approximate total population from the three education tiers."""
    return (df[f"nodiph{year}"] + df[f"nodipf{year}"] +
            df[f"bach{year}"]   + df[f"bacf{year}"]   +
            df[f"suph{year}"]   + df[f"supf{year}"])

def compute_gender_gap(df, year):
    """Tertiary-education share among men minus among women (pre-treatment year)."""
    tertiary_m = df[f"bach{year}"] + df[f"suph{year}"]
    tertiary_f = df[f"bacf{year}"] + df[f"supf{year}"]
    total_m = tertiary_m + df[f"nodiph{year}"]
    total_f = tertiary_f + df[f"nodipf{year}"]
    return (tertiary_m / total_m) - (tertiary_f / total_f)

def compute_no_diploma_share(df, year):
    """Share of residents with no diploma (pre-treatment year)."""
    no_diploma = df[f"nodiph{year}"] + df[f"nodipf{year}"]
    total = no_diploma + df[f"bach{year}"] + df[f"bacf{year}"] + df[f"suph{year}"] + df[f"supf{year}"]
    return no_diploma / total

In [7]:
# Each tuple: (election_year, pre2_year, pre_year, post_year)
#   pre-trend (placebo, post=0): pre2 -> pre  (entirely BEFORE the election)
#   treatment (post=1):          pre  -> post (spans the election)
# 2014: real census years only (2006, 2011, 2016) -> 5-year changes.
# 2020: values are overwritten with real INSEE census data (2010 -> 2015 -> 2021) further below.
windows = [
    (2008, 1999, 2004, 2009),   # excluded from estimation (no treated units), kept for completeness
    (2014, 2006, 2011, 2016),   # real census years
    (2020, 2016, 2019, 2022),   # placeholder, overwritten by INSEE
]

In [8]:
rows = []
for election_year, pre2_y, pre_y, post_y in windows:
    # Compute skill share at pre- and post-election census
    share_pre  = compute_skill_share(df_edu, pre_y)
    share_post = compute_skill_share(df_edu, post_y)
    # Delta = change in educated share around the election
    delta = share_post - share_pre

    # Carry population at both waves forward — filtering happens later, not here
    pop_pre  = compute_total_pop(df_edu, pre_y)
    pop_post = compute_total_pop(df_edu, post_y)

    # Build one df for this election year
    tmp = pd.DataFrame({
        "commune_id":          df_edu["codecommune"],
        "election_year":       election_year,
        "skill_share_pre":     share_pre,
        "skill_share_trend":   compute_skill_share_trend(df_edu, pre2_y, pre_y),
        "delta_skill_share":   delta,
        "pop_pre":             pop_pre,
        "pop_post":            pop_post,
        "gender_gap_tertiary": compute_gender_gap(df_edu, pre_y),
        "no_diploma_share":    compute_no_diploma_share(df_edu, pre_y),
    })
    rows.append(tmp)

df_outcome = pd.concat(rows, ignore_index=True)

In [9]:
# 2020 cycle: replace extrapolated Cagé-Piketty outcomes with real INSEE census data
f = 'base-cc-diplomes-formation-2021.xlsx'
edu_cols = {'10': ['BAC', 'BACP2', 'SUP'], '15': ['BAC', 'SUP'], '21': ['BAC', 'SUP2', 'SUP34', 'SUP5']}  # bac or higher
sheets = {yy: pd.read_excel(f, sheet_name=f'COM_20{yy}', header=5, dtype={'CODGEO': str}).set_index('CODGEO')
          for yy in edu_cols}

def insee_share(yy, sex=''):
    """Share with bac or higher among non-students 15+ (sex='' all, 'F' women)."""
    d = sheets[yy]
    return sum(d[f'P{yy}_{sex}NSCOL15P_{c}'] for c in edu_cols[yy]) / d[f'P{yy}_{sex}NSCOL15P']

m = df_outcome['election_year'] == 2020                        # overwrite ONLY the 2020 rows
df_outcome.loc[m, 'skill_share_trend'] = df_outcome.loc[m, 'commune_id'].map(insee_share('15') - insee_share('10'))
df_outcome.loc[m, 'delta_skill_share'] = df_outcome.loc[m, 'commune_id'].map((insee_share('21') - insee_share('15')) * 5 / 6)

In [10]:
# Second pre-period (2014 cycle only): 1999 -> 2006, both real census years
# 2020 cycle stays NaN: no clean earlier point in the INSEE series.
trend2 = pd.Series(
    (compute_skill_share(df_edu, 2006) - compute_skill_share(df_edu, 1999)).values,
    index=df_edu['codecommune'],
)
assert trend2.index.is_unique, "duplicate commune codes in df_edu"

df_outcome = df_outcome.drop(columns='skill_share_trend2', errors='ignore')   # safe re-run
df_outcome['skill_share_trend2'] = np.nan
m = df_outcome['election_year'] == 2014
df_outcome.loc[m, 'skill_share_trend2'] = df_outcome.loc[m, 'commune_id'].map(trend2)

print(df_outcome.loc[m, 'skill_share_trend2'].describe())   # mean should be positive (educational expansion)

count    36558.000000
mean         0.089309
std          0.103917
min         -1.000000
25%          0.038065
50%          0.085423
75%          0.138889
max          1.000000
Name: skill_share_trend2, dtype: float64

In [11]:
df_outcome.head(3)

,commune_id,election_year,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2
0,01001,2008,0.285171,0.149578,0.094717,526.0,537.0,0.039127,0.714829,NaN
1,01002,2008,0.381944,0.123880,0.145002,144.0,167.0,0.019276,0.618056,NaN
2,01003,2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Source (French Electoral outcomes)
- https://www.data.gouv.fr/datasets/donnees-des-elections-agregees

In [12]:
# Load the full candidats file
# Large file low_memory=False prevents dtype warnings
df_cand = pd.read_csv("candidats_results.csv", sep=";", encoding="latin-1", low_memory=False)

In [13]:
# Standardise commune code to 5 characters (leading zeros)
df_cand["code_commune"] = df_cand["code_commune"].str.zfill(5)

In [14]:
# Inspect all unique nuance codes
print(df_cand["nuance"].unique())

['LDVC' 'LDVD' nan 'LDIV' 'LRN' 'LDVG' 'LUG' 'LUD' 'LCOM' 'LUXD' 'LLR'
 'LFI' 'LEXD' 'LEXG' 'LREG' 'LUC' 'LUDR' 'LSOC' 'LUDI' 'LECO' 'LVEC'
 'LHOR' 'LREN' 'LMDM' 'LREC' 'LDSV' 'DXG' 'DVG' 'DIV' 'REG' 'ECO' 'NUP'
 'RDG' 'ENS' 'LR' 'DVC' 'DSV' 'DVD' 'UDI' 'REC' 'RN' 'DXD' 'REM' 'MDM'
 'FN' 'SOC' 'COM' 'FI' 'EXD' 'DLF' 'EXG' 'NC' 'LNC' 'LREM' 'LDLF' 'LGJ'
 'BC-UCD' 'BC-UG' 'BC-RN' 'BC-UD' 'BC-UGE' 'BC-UXD' 'BC-LR' 'BC-DVD'
 'BC-DVG' 'BC-DVC' 'BC-DIV' 'BC-RDG' 'BC-SOC' 'BC-COM' 'BC-UC' 'BC-REM'
 'BC-UCG' 'BC-ECO' 'BC-UDI' 'BC-MDM' 'BC-EXD' 'BC-FI' 'BC-EXG' 'BC-REG'
 'BC-DSV' 'BC-GJ' 'LAUT' 'LMAJ' 'LGC' 'LMC' 'LCMD' 'LFN' 'UG' 'UXD' 'HOR'
 'VEC' 'LENS' 'LRDG' 'LVEG' 'LFG' 'LUGE' 'LUCD' 'UMP' 'MNR' 'PREP' 'MPF'
 'LO' 'LCR' 'CPNT' 'RPF' 'PRG' 'UDF' 'DL' 'LCOP' 'RPR' 'MDC' 'UDFD' 'M-NC'
 'AUT' 'MNA' 'GAU' 'FRN' 'DTE' 'LDV' 'LDD' 'LPC' 'LXD' 'LUDF' 'LUMP' 'LPS'
 'LCP' 'LRG' 'LXG' 'LVE' 'LDG' 'LEC' 'LGA' 'LDR' 'PG' 'M' 'MODM' 'BOVE'
 'BUFF' 'SCHI' 'LAGU' 'VILL' 'VOYN' 'BAYR' 'BESA' 'ROYA' 'SARK' 'NIHO'
 'LEPE' 'MEGR' 'LEPA' 'GLUC' 'CHIR' 'TAUB' 'SAIN' 'MAME' 'JOSP' 'BOUT'
 'HUE' 'CHEV' 'MADE' 'BC-FN' 'BC-VEC' 'BC-UMP' 'BC-FG' 'BC-DLF' 'BC-PG'
 'MAJ' 'NCE' 'PRV' 'FG' 'CEN' 'ALLI' 'JOLY' 'MELE' 'HOLL' 'DUPO' 'CHEM'
 'ARTH' 'POUT' 'LPG']

#### Defining far right code names 
| Code    | Full Name                       | Years Active          |
|---------|---------------------------------|-----------------------|
| RN      | Rassemblement National          | 2020, 2026            |
| LRN     | Liste Rassemblement National    | 2020, 2026            |
| BC-RN   | Binôme/coalition RN             | 2020, 2026            |
| FN      | Front National                  | 2008, 2014            |
| FRN     | Front National                  | 2008, 2014, 2020      |
| LFN     | Liste Front National            | 2008, 2014            |
| BC-FN   | Binôme FN                       | 2014                  |
| EXD     | Extrême droite (generic)        | all years             |
| LEXD    | Liste extrême droite            | all years             |
| BC-EXD  | Binôme extrême droite           | 2014, 2020            |
| DXD     | Divers extrême droite           | all years             |
| LUXD    | Liste union extrême droite      | 2020, 2026            |
| UXD     | Union extrême droite            | all years             |
| BC-UXD  | Binôme union extrême droite     | 2014, 2020            |
| MNR     | Mouvement National Républicain  | 2008                  |

In [15]:
# Keep only the columns needed, drop the rest as the df is too big otherwise
df_slim = df_cand[[
    "id_election",    # year + round identifier
    "code_commune",   # municipality code
    "nuance",         # party affiliation
    "voix",           # vote count
]].copy()

In [16]:
df_slim.head(3)

    id_election code_commune nuance  voix
0  2026_muni_t2        01160   LDVC   257
1  2026_muni_t2        01160   LDVC   311
2  2026_muni_t2        01160   LDVC   252

In [17]:
# Parse year and round and add them as new columns
df_slim["election_year"] = df_slim["id_election"].str.split("_").str[0].astype(int)
df_slim["tour"]          = df_slim["id_election"].str.split("_").str[2]

# Keep only municipal elections
df_slim = df_slim[df_slim["id_election"].str.contains("muni")].drop(columns="id_election")

# Export, hence create a new file with only the columns needed for the RDD analysis
df_slim.to_csv("candidats_slim.csv", index=False)

In [18]:
df_slim.head(3)

  code_commune nuance  voix  election_year tour
0        01160   LDVC   257           2026   t2
1        01160   LDVC   311           2026   t2
2        01160   LDVC   252           2026   t2

In [19]:
# Define far-right nuance codes
far_right_nuances = [
    "RN", "LRN", "BC-RN",           # Rassemblement National (2020, 2026)
    "FN", "LFN", "BC-FN", "FRN"     # Front National (2008, 2014)
    "EXD", "LEXD", "BC-EXD",        # Extrême droite generic
    "DXD", "LUXD", "UXD", "BC-UXD", # Union / divers extrême droite
    "MNR",                          # Mégret splinter (2008)
]

# Possible that not all these nuances are present in the dataset, but we can still flag them if they are.

# Flag far-right rows
df_slim["is_far_right"] = df_slim["nuance"].isin(far_right_nuances)

In [20]:
# I do not use data from year 2026 right now
df_slim = df_slim[df_slim["election_year"] != 2026]

In [21]:
# Calculate share of far-right rows
far_right_share = df_slim["is_far_right"].mean() * 100
print(f"Share of far-right candidates: {far_right_share:.2f}%")

# Also show counts
print(f"\nCounts:")
print(df_slim["is_far_right"].value_counts())
print(f"\nTotal rows: {len(df_slim):,}")

Share of far-right candidates: 2.69%

Counts:
is_far_right
False    1424106
True       39424
Name: count, dtype: int64

Total rows: 1,463,530

In [22]:
# Determine the decisive round per commune/year
#    (max tour number: 2 > 1)
df_slim['tour_num'] = df_slim['tour'].str.extract('(\d+)').astype(int)

# Get the highest tour number for each (commune, year)
decisive_rounds = (
    df_slim.groupby(['code_commune', 'election_year'])['tour_num']
    .max()
    .reset_index(name='decisive_tour')
)

# Keep only rows that belong to that decisive round
df_dec = df_slim.merge(decisive_rounds, on=['code_commune', 'election_year'], how='inner')
df_dec = df_dec[df_dec['tour_num'] == df_dec['decisive_tour']]

<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
C:\Users\tobia\AppData\Local\Temp\ipykernel_10808\2142661507.py:3: SyntaxWarning: invalid escape sequence '\d'
  df_slim['tour_num'] = df_slim['tour'].str.extract('(\d+)').astype(int)

In [23]:
# Identify the winner in each decisive round
#    (row with maximum voix)
winner_idx = df_dec.groupby(['code_commune', 'election_year'])['voix'].idxmax()
df_winners = df_dec.loc[winner_idx].copy()

In [24]:
df_winners.head(3)

,code_commune,nuance,voix,election_year,tour,is_far_right,tour_num,decisive_tour
771511,01001,NC,331,2014,t1,False,1,1
452703,01001,NC,267,2020,t1,False,1,1
771524,01002,NC,165,2014,t1,False,1,1

In [25]:
# ── Recreate treat column (1 = far-right won the decisive round, 0 = otherwise) ──
# df_winners should already contain only ONE row per commune x election_year
# (the winning list, selected via idxmax on voix). If so, is_far_right IS treat.
df_winners['treat'] = df_winners['is_far_right'].astype(int)

# Sanity check: one row per commune x election_year, and reasonable win count
print(df_winners.groupby(['code_commune', 'election_year']).size().max())  # should be 1
print(df_winners['treat'].sum())  # should match your earlier count (26)

1
26

When does a winner get <50%?

In French municipal elections, when 3+ lists contest the decisive round, votes split across them. The winner only needs a plurality (most votes), not an absolute majority (>50%). Example: three lists get 40%/35%/25% — the 40% list wins despite most voters (60%) voting against it.

This happens routinely in French municipal races (multi-list contests are common, especially in larger communes), so a meaningful share of your winners will be below 50%.

In [26]:
# creating the d_50 variable (plurality margin) for each commune x year, in percentage points

# Step 1: total votes cast per commune x year (decisive round only) 
total_votes = (
    df_dec.groupby(['code_commune', 'election_year'])['voix']
    .sum()
    .reset_index(name='voix_total')
)

# Step 2: far-right votes per commune x year (0 if no far-right list ran) 
# (if multiple far-right lists ran in one commune, they get added together).
far_right_votes = (
    df_dec[df_dec['is_far_right']]
    .groupby(['code_commune', 'election_year'])['voix']
    .max() # get the maximum votes for any far-right list in the decisive round
    .reset_index(name='voix_far_right')
)

# Step 3: best NON-far-right list's votes per commune x year
# (this is who the far-right actually had to beat)
runner_up_votes = (
    df_dec[~df_dec['is_far_right']]
    .groupby(['code_commune', 'election_year'])['voix']
    .max() # instead of sum, we want the best rival's votes
    .reset_index(name='voix_runner_up')
)

# Step 4: merge total votes, far-right votes, and runner-up votes into one table
margin_table = (
    total_votes # is the base table, since it contains all commune x year combinations
    .merge(far_right_votes, on=['code_commune', 'election_year'], how='left')
    .merge(runner_up_votes, on=['code_commune', 'election_year'], how='left')
    .fillna(0)  # communes with no far-right list -> voix_far_right = 0
)

# Step 5: compute d_50 as the plurality margin, in percentage points
# (far-right share − best-rival share) x 100
margin_table['d_50'] = (
    (margin_table['voix_far_right'] - margin_table['voix_runner_up']) / margin_table['voix_total']
) * 100 # as percentage points

# Step 6: drop any stale d_50 in df_winners, then merge in the new one cleanly
df_winners = df_winners.drop(columns=['d_50'], errors='ignore').merge(
    margin_table[['code_commune', 'election_year', 'd_50']],
    on=['code_commune', 'election_year'],
    how='left'
)

In [27]:
df_winners.head(3)

,code_commune,nuance,voix,election_year,tour,is_far_right,tour_num,decisive_tour,treat,d_50
0,01001,NC,331,2014,t1,False,1,1,0,-7.090831
1,01001,NC,267,2020,t1,False,1,1,0,-6.964006
2,01002,NC,165,2014,t1,False,1,1,0,-9.939759

## Merge electoral with educational Data

In [28]:
df_winners.head(3)

,code_commune,nuance,voix,election_year,tour,is_far_right,tour_num,decisive_tour,treat,d_50
0,01001,NC,331,2014,t1,False,1,1,0,-7.090831
1,01001,NC,267,2020,t1,False,1,1,0,-6.964006
2,01002,NC,165,2014,t1,False,1,1,0,-9.939759

In [29]:
df_outcome.tail(3)

,commune_id,election_year,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2
113952,95680,2020,0.402168,0.023435,0.041153,16513.0,16493.0,-0.045364,0.597832,NaN
113953,95682,2020,0.282051,0.032819,0.068478,156.0,172.0,-0.387075,0.717949,NaN
113954,95690,2020,0.792453,0.047416,0.026373,265.0,273.0,0.012847,0.207547,NaN

In [30]:
# 1. Standardise both keys to 5-digit strings (this fixes the type mismatch)
df_winners['code_commune'] = df_winners['code_commune'].astype(str).str.zfill(5)
df_outcome['commune_id'] = df_outcome['commune_id'].astype(str).str.zfill(5)

In [31]:
# 2. Merge on both commune and year
df_merged = df_winners.merge(
    df_outcome,
    how='left',  # Keep all winners, even if outcome is missing
    left_on=['code_commune', 'election_year'],
    right_on=['commune_id', 'election_year']
)

In [32]:
# 3. sanity check
print(f"Total winners: {len(df_winners)}")
print(f"Rows after merge: {len(df_merged)}")
print(f"Rows with missing outcome: {df_merged['delta_skill_share'].isna().sum()}")

Total winners: 74370
Rows after merge: 74370
Rows with missing outcome: 1922

In [33]:
df_merged.head(3)

,code_commune,nuance,voix,election_year,tour,is_far_right,tour_num,decisive_tour,treat,d_50,commune_id,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2
0,01001,NC,331,2014,t1,False,1,1,0,-7.090831,01001,0.409091,0.073324,0.018182,528.0,550.0,-0.042710,0.590909,0.200173
1,01001,NC,267,2020,t1,False,1,1,0,-6.964006,01001,0.437943,0.012418,0.059144,564.0,576.0,0.027476,0.562057,NaN
2,01002,NC,165,2014,t1,False,1,1,0,-9.939759,01002,0.590909,0.169856,0.037662,176.0,175.0,-0.016667,0.409091,0.162988

In [34]:
# Drop unnecessary columns (tour_num, decisive_tour, commune_id) after the merge
df_merged = df_merged.drop(columns=["tour_num", "decisive_tour", "commune_id"])

In [35]:
# Quick check of treat dummy distribution
df_merged['treat'].value_counts()

treat
0    74344
1       26
Name: count, dtype: int64

In [36]:
# Drop al entries with no far-right participation in the decisive round
# I only need rounds where the far-right actually fielded a list, otherwise the RDD is not well-defined.

# Add a participation flag (True if far-right fielded any list in the decisive round)
participation = (
    df_dec.groupby(['code_commune', 'election_year'])['is_far_right']
    .any()
    .reset_index(name='far_right_participated')
)

# add to df_merged
df_merged = df_merged.merge(
    participation, on=['code_commune', 'election_year'], how='left'
)

# Filter to far-right participants only (drop the rest)
df_rdd = df_merged[df_merged['far_right_participated']].copy()
print(f"N observations in RDD sample: {len(df_rdd)}")
print(f"N far-right wins (treat=1): {df_rdd['treat'].sum()}")

N observations in RDD sample: 843
N far-right wins (treat=1): 26

In [37]:
# Filter out communes with very small populations (pre- or post-election)
min_pop = 100
df_rdd = df_rdd[(df_rdd['pop_pre'] >= min_pop) & (df_rdd['pop_post'] >= min_pop)].copy()

## Population Growth

In [38]:
# ── Covariate: pre-election population growth (log change), genuine census anchors only ──
# Population proxy = residents 15+ from the education tiers (compute_total_pop), not total population.
# 2014 cycle: 2006 -> 2011 | 2020 cycle: 2011 -> 2016 (2008 is excluded from estimation anyway)
growth_windows = {2014: (2006, 2011), 2020: (2011, 2016)}

rows = []
for election_year, (y0, y1) in growth_windows.items():
    rows.append(pd.DataFrame({
        'code_commune':  df_edu['codecommune'],
        'election_year': election_year,
        'pop_growth':    np.log(compute_total_pop(df_edu, y1)) - np.log(compute_total_pop(df_edu, y0)),
    }))
df_growth = pd.concat(rows, ignore_index=True).replace([np.inf, -np.inf], np.nan)

# drop() first so re-running the cell doesn't create _x/_y duplicates
df_rdd = df_rdd.drop(columns='pop_growth', errors='ignore').merge(
    df_growth, on=['code_commune', 'election_year'], how='left')
print(df_rdd.groupby('election_year')['pop_growth'].agg(['count', 'mean']))

               count      mean
election_year
2008               0       NaN
2014             513  0.026980
2020             285  0.035435

c:\Users\tobia\anaconda3\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

## Add Economic Data

**Data Sources:**

**Insee** Institut national de la statistique et des études économiques, declared income (DEC)

- Data from 2008: https://www.insee.fr/fr/statistiques/1893295?sommaire=2389000
- Data from 2014: https://www.insee.fr/fr/statistiques/3288151
- Data from 2020: https://www.insee.fr/fr/statistiques/7233950

In [39]:
# Commune list you actually need (from df_rdd)
communes_needed = set(df_rdd['code_commune'].astype(str).str.zfill(5))

In [40]:
# import 2008 dataframe
# RFDU2008COM.xls (commune-level, 2008)
df_2008 = pd.read_excel(
    'RFDU2008COM.xls',
    sheet_name='D_UC',
    header=6  # real header is on row 7 (0-indexed row 6)
)

df_2008['COM'] = df_2008['COM'].astype(str).str.zfill(5)
df_2008 = df_2008[df_2008['COM'].isin(communes_needed)]
df_2008 = df_2008[['COM', 'RFUCQ208', 'RFUCGI08']]  # keep median + gini only
df_2008 = df_2008.rename(columns={'COM': 'code_commune', 'RFUCQ208': 'income_median_2008', 'RFUCGI08': 'income_gini_2008'})

In [41]:
# Create function to load IRIS income data for 2014 and 2020, aggregate to commune level, and handle French decimal commas + suppression markers ("ns", "nd").
# IRIS files (2014 & 2020) — need IRIS → commune aggregation
def load_iris_income(path, sheet, header_row, med_col, gini_col, year):
    df = pd.read_excel(path, sheet_name=sheet, header=header_row)
    df['COM'] = df['COM'].astype(str).str.zfill(5)
    df = df[df['COM'].isin(communes_needed)]

    # Fix French comma decimals and confidentiality markers ("ns", "nd") if present
    for col in [med_col, gini_col]:
        if df[col].dtype == object:
            df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')  # "ns"/"nd" -> NaN instead of crashing

    # Aggregate IRIS -> commune (simple mean for now, see caveat below)
    df_com = (
        df.groupby('COM')[[med_col, gini_col]].mean()
        .reset_index()
        .rename(columns={
            'COM': 'code_commune',
            med_col: f'income_median_{year}',
            gini_col: f'income_gini_{year}',
        })
    )
    return df_com

In [42]:
#Import data, run the function for 2014 and 2020

# 2014 — declared income (DEC), comparable to RFL 2008's "revenu fiscal" concept
df_2014 = load_iris_income(
    'BASE_TD_FILO_DEC_IRIS_2014.xls', 'IRIS_DEC',
    header_row=5, med_col='DEC_MED14', gini_col='DEC_GI14', year=2014
)

# 2020 — declared income (DEC)
df_2020 = load_iris_income(
    'BASE_TD_FILO_DEC_IRIS_2020.xlsx', 'IRIS_DEC',
    header_row=5, med_col='DEC_MED20', gini_col='DEC_GI20', year=2020
)

In [43]:
# Merge and standardize the income dataframes for 2008, 2014, and 2020 into df_rdd

# Add election_year to each df and standardize column names ──
df_2008 = df_2008.rename(columns={'income_median_2008': 'income_median', 'income_gini_2008': 'income_gini'})
df_2008['election_year'] = 2008

df_2014 = df_2014.rename(columns={'income_median_2014': 'income_median', 'income_gini_2014': 'income_gini'})
df_2014['election_year'] = 2014

df_2020 = df_2020.rename(columns={'income_median_2020': 'income_median', 'income_gini_2020': 'income_gini'})
df_2020['election_year'] = 2020

# Stack into one long df ──
df_income = pd.concat([df_2008, df_2014, df_2020], ignore_index=True)

# Merge into df_rdd on code_commune + election_year ──
df_rdd = df_rdd.merge(df_income, on=['code_commune', 'election_year'], how='left')

In [44]:
df_rdd

,code_commune,nuance,voix,election_year,tour,is_far_right,treat,d_50,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2,far_right_participated,pop_growth,income_median,income_gini
0,01053,LUG,437,2014,t1,False,0,-2.409639,0.392705,0.020687,0.023270,27491.52580,28388.73630,-0.010252,0.607295,0.056592,True,-0.001254,17694.500000,0.365057
1,01053,LUG,388,2020,t1,False,0,-4.088756,0.429253,0.021263,0.035516,28927.00000,29466.00000,0.001390,0.570747,NaN,True,0.032115,18276.111111,0.375722
2,02168,LDVG,335,2014,t1,False,0,-5.130327,0.345043,0.057388,-0.009702,9931.99378,10209.33112,-0.007876,0.654957,0.051668,True,0.006740,17063.666667,0.368367
3,02168,LDVC,264,2020,t1,False,0,-5.420827,0.329670,0.015058,0.007888,10374.00000,10542.00000,-0.068924,0.670330,NaN,True,0.027541,17170.000000,0.387833
4,02173,LDVD,315,2014,t2,False,0,-4.599702,0.300207,0.059974,0.024026,8128.33600,8180.49583,0.026023,0.699793,0.050191,True,-0.041324,15662.666667,0.399675
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,95491,LDVD,386,2014,t1,False,0,-8.980798,0.523774,0.058217,0.034841,5300.00000,5630.00000,-0.022657,0.476226,0.098478,True,0.003023,NaN,NaN
833,95563,LUMP,411,2014,t1,False,0,-5.092448,0.550017,0.032736,0.034497,10133.39774,10584.24178,-0.005706,0.449983,0.103071,True,0.021183,28190.666667,0.309148
834,95607,LUG,344,2008,t1,False,0,-3.158237,0.430999,0.062273,0.049311,17007.00000,17293.00000,0.006453,0.569001,NaN,True,NaN,22209.000000,0.309100
835,95607,LUMP,462,2014,t2,False,0,-3.745754,0.496955,0.041926,0.031564,17368.41700,17593.45260,0.012162,0.503045,0.086303,True,0.010958,23755.090909,0.303520
836,95607,LDVD,294,2020,t1,False,0,-3.814262,0.547101,0.040733,0.034929,17728.00000,17863.00000,-0.002802,0.452899,NaN,True,0.012873,25021.818182,0.308000

In [45]:
# Break missingness down by year AND by variable separately
print(df_rdd.groupby('election_year')[['income_median', 'income_gini']].apply(lambda x: x.isna().sum()))

# And total rows per year, for context
print(df_rdd['election_year'].value_counts())

               income_median  income_gini
election_year
2008                       0            0
2014                     168          168
2020                      29           29
election_year
2014    513
2020    285
2008     39
Name: count, dtype: int64

"FiLoSoFi's declared-income (DEC) product had substantially narrower national commune coverage in its 2014 vintage (969 communes) compared to 2020 (1,887 communes), resulting in 225 sample communes (168 commune-election observations) lacking 2014 income data. This asymmetry is disclosed in the balance-check results by reporting the effective N for each election cycle rather than assuming complete coverage."

## Add Unemployment Data

**Data Sources:**

**Insee** Institut national de la statistique et des études économiques, Employment - working population

- Data from 2008: https://www.insee.fr/fr/statistiques/2044654
- Data from 2014: https://www.insee.fr/fr/statistiques/2862207
- Data from 2020: https://www.insee.fr/fr/statistiques/7632867

Unemployment comuptation: **CHOM / ACT**
- total **active** pop. (15-64yrs): P08_**ACT**1564 (2008)
- total **unemployed** pop. (15-64yrs): P08_**CHOM**1564 (2008)

In [46]:
# function to load employment data, compute unemployment rate, and standardize commune codes.

# Same defensive handling as income (French decimal commas + "ns"/"nd" suppression markers) in case they appear.
def load_unemployment(path, sheet, header_row, act_col, chom_col, year): # navigate to the correct sheet, header row, and column names for each year
    df = pd.read_excel(path, sheet_name=sheet, header=header_row)
    df['CODGEO'] = df['CODGEO'].astype(str).str.zfill(5)
    df = df[df['CODGEO'].isin(communes_needed)] # only keep communes that are actually in the RDD sample

    # Fix French comma decimals and confidentiality markers ("ns", "nd") if present
    for col in [act_col, chom_col]:
        if df[col].dtype == object:
            df[col] = df[col].astype(str).str.replace(',', '.', regex=False)
            df[col] = pd.to_numeric(df[col], errors='coerce')  # "ns"/"nd" -> NaN instead of crashing

    # Unemployment rate = chômeurs / actifs (15-64), in %
    df['unemployment_rate'] = (df[chom_col] / df[act_col]) * 100

    df_com = df[['CODGEO', 'unemployment_rate']].rename(columns={'CODGEO': 'code_commune'})
    df_com['election_year'] = year
    return df_com

In [47]:
# 2008
df_unemp_2008 = load_unemployment(
    'base-cc-emploi-pop-active-2008.xls', 'COM_2008',
    header_row=5, act_col='P08_ACT1564', chom_col='P08_CHOM1564', year=2008
)

# 2014
df_unemp_2014 = load_unemployment(
    'base-cc-emploi-pop-act-2014.xls', 'COM_2014',
    header_row=5, act_col='P14_ACT1564', chom_col='P14_CHOM1564', year=2014
)

# 2020
df_unemp_2020 = load_unemployment(
    'base-cc-emploi-pop-active-2020_v2.xlsx', 'COM_2020',
    header_row=5, act_col='P20_ACT1564', chom_col='P20_CHOM1564', year=2020
)

In [48]:
# Stack into one long df, matching the income_df pattern
df_unemployment = pd.concat([df_unemp_2008, df_unemp_2014, df_unemp_2020], ignore_index=True)

# Merge into df_rdd on code_commune + election_year
df_rdd = df_rdd.merge(df_unemployment, on=['code_commune', 'election_year'], how='left')

In [49]:
df_rdd

,code_commune,nuance,voix,election_year,tour,is_far_right,treat,d_50,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2,far_right_participated,pop_growth,income_median,income_gini,unemployment_rate
0,01053,LUG,437,2014,t1,False,0,-2.409639,0.392705,0.020687,0.023270,27491.52580,28388.73630,-0.010252,0.607295,0.056592,True,-0.001254,17694.500000,0.365057,17.997301
1,01053,LUG,388,2020,t1,False,0,-4.088756,0.429253,0.021263,0.035516,28927.00000,29466.00000,0.001390,0.570747,NaN,True,0.032115,18276.111111,0.375722,17.078005
2,02168,LDVG,335,2014,t1,False,0,-5.130327,0.345043,0.057388,-0.009702,9931.99378,10209.33112,-0.007876,0.654957,0.051668,True,0.006740,17063.666667,0.368367,22.861113
3,02168,LDVC,264,2020,t1,False,0,-5.420827,0.329670,0.015058,0.007888,10374.00000,10542.00000,-0.068924,0.670330,NaN,True,0.027541,17170.000000,0.387833,23.566623
4,02173,LDVD,315,2014,t2,False,0,-4.599702,0.300207,0.059974,0.024026,8128.33600,8180.49583,0.026023,0.699793,0.050191,True,-0.041324,15662.666667,0.399675,24.051101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
832,95491,LDVD,386,2014,t1,False,0,-8.980798,0.523774,0.058217,0.034841,5300.00000,5630.00000,-0.022657,0.476226,0.098478,True,0.003023,NaN,NaN,8.661228
833,95563,LUMP,411,2014,t1,False,0,-5.092448,0.550017,0.032736,0.034497,10133.39774,10584.24178,-0.005706,0.449983,0.103071,True,0.021183,28190.666667,0.309148,10.062158
834,95607,LUG,344,2008,t1,False,0,-3.158237,0.430999,0.062273,0.049311,17007.00000,17293.00000,0.006453,0.569001,NaN,True,NaN,22209.000000,0.309100,8.712611
835,95607,LUMP,462,2014,t2,False,0,-3.745754,0.496955,0.041926,0.031564,17368.41700,17593.45260,0.012162,0.503045,0.086303,True,0.010958,23755.090909,0.303520,10.358991
836,95607,LDVD,294,2020,t1,False,0,-3.814262,0.547101,0.040733,0.034929,17728.00000,17863.00000,-0.002802,0.452899,NaN,True,0.012873,25021.818182,0.308000,10.931071

## Add Data about Immigration and age structure

**Data Sources:**

**Insee** Institut national de la statistique et des études économiques, Employment - working population

- Data from 2011 (pooled census from 2009-2013): https://www.insee.fr/fr/statistiques/2048172?sommaire=2404835
- Data from 2014 (pooled census from 2002-2016): https://www.insee.fr/fr/statistiques/2863598?sommaire=2867837

**Definition INSEE** _Immigrant (INSEE) = person born abroad as a foreigner, regardless of nationality today (can be French by naturalisation)._




Foreign-born share computation: **IMMI1 / ALL** × 100
- total **immigrant** pop. (all ages, both sexes): sum of the 8 columns `AGE4xx_**IMMI1**_SEXEx`
- total pop. (all ages, both sexes): sum of all 16 columns `AGE4xx_IMMIx_SEXEx`



Age structure: **AGE / ALL** × 100 (same table)
- share **55+**: sum of columns `AGE455_IMMIx_SEXEx` / total pop.
- share **15–24**: sum of columns `AGE415_IMMIx_SEXEx` / total pop.

In [50]:
# ── Foreign-born share + age structure, 2011 census (used for the 2014 election cycle) ──
# ONE cell only: everything happens on the raw table, and the slimming-down (step 8) comes LAST.

# 1. Load the sheet 'COM' (one row per commune); real column names are on the 9th Excel row -> header=8
df_imm_2011 = pd.read_excel(
    'BTX_TD_IMG1A_2011.xls',
    sheet_name='COM',
    header=8,
    dtype={'CODGEO': str}       # keep the commune code as text ('01001', not 1001)
)

# 2. 5-character commune codes (leading zeros)
df_imm_2011['CODGEO'] = df_imm_2011['CODGEO'].str.zfill(5)

# 3. The table has 16 head-count columns named like AGE400_IMMI1_SEXE1:
#      AGE4xx = age group (00 = <15, 15 = 15-24, 25 = 25-54, 55 = 55+)
#      IMMI1  = immigrants, IMMI2 = non-immigrants | SEXE1/2 = men / women

# 4. Numerator: all immigrants = sum of every column containing 'IMMI1' (8 columns)
immigrants_2011 = df_imm_2011.filter(like='IMMI1').sum(axis=1)

# 5. Denominator: total population = sum of ALL 16 count columns
population_2011 = df_imm_2011.drop(columns=['CODGEO', 'LIBGEO']).sum(axis=1)

# 6. Foreign-born share in %
df_imm_2011['foreign_population'] = immigrants_2011 / population_2011 * 100

# 6b. Age structure (same table): AGE455_* = 55+ (4 columns), AGE415_* = 15-24 (4 columns)
df_imm_2011['share_55plus'] = df_imm_2011.filter(like='AGE455').sum(axis=1) / population_2011 * 100
df_imm_2011['share_15_24']  = df_imm_2011.filter(like='AGE415').sum(axis=1) / population_2011 * 100

# 7. Quick checks: national foreign-born share (~8.6) and means of the three variables (roughly 4 / 33 / 9, NOT 0)
print('2011 national share (%):', round(immigrants_2011.sum() / population_2011.sum() * 100, 2))
print(df_imm_2011[['foreign_population', 'share_55plus', 'share_15_24']].mean().round(1))

# 8. LAST step: keep only what we need (CODGEO is renamed here, so nothing may use it afterwards)
df_imm_2011 = df_imm_2011[['CODGEO', 'foreign_population', 'share_55plus', 'share_15_24']].rename(columns={'CODGEO': 'code_commune'})
df_imm_2011['election_year'] = 2014

2011 national share (%): 8.63
foreign_population     4.0
share_55plus          33.2
share_15_24            9.2
dtype: float64

In [51]:
# ── Foreign-born share + age structure, 2014 census (used for the 2020 election cycle) ──
# ONE cell only: everything happens on the raw table, and the slimming-down (step 8) comes LAST.
# Same steps as the 2011 cell. Only difference: this file has one more title line, so header=10.

# 1. Load the sheet 'COM' (one row per commune)
df_imm_2014 = pd.read_excel(
    'BTX_TD_IMG1A_2014.xls',
    sheet_name='COM',
    header=10,
    dtype={'CODGEO': str}       # keep the commune code as text ('01001', not 1001)
)

# 2. 5-character commune codes (leading zeros)
df_imm_2014['CODGEO'] = df_imm_2014['CODGEO'].str.zfill(5)

# 3. Numerator: all immigrants = sum of every column containing 'IMMI1' (8 columns)
immigrants_2014 = df_imm_2014.filter(like='IMMI1').sum(axis=1)

# 4. Denominator: total population = sum of ALL 16 count columns
population_2014 = df_imm_2014.drop(columns=['CODGEO', 'LIBGEO']).sum(axis=1)

# 5. Foreign-born share in %
df_imm_2014['foreign_population'] = immigrants_2014 / population_2014 * 100

# 5b. Age structure (same table): AGE455_* = 55+ (4 columns), AGE415_* = 15-24 (4 columns)
df_imm_2014['share_55plus'] = df_imm_2014.filter(like='AGE455').sum(axis=1) / population_2014 * 100
df_imm_2014['share_15_24']  = df_imm_2014.filter(like='AGE415').sum(axis=1) / population_2014 * 100

# 6. Quick checks: national foreign-born share (~9.05) and means of the three variables (roughly 4 / 35 / 9, NOT 0)
print('2014 national share (%):', round(immigrants_2014.sum() / population_2014.sum() * 100, 2))
print(df_imm_2014[['foreign_population', 'share_55plus', 'share_15_24']].mean().round(1))

# 7. LAST step: keep only what we need (CODGEO is renamed here, so nothing may use it afterwards)
df_imm_2014 = df_imm_2014[['CODGEO', 'foreign_population', 'share_55plus', 'share_15_24']].rename(columns={'CODGEO': 'code_commune'})
df_imm_2014['election_year'] = 2020      # the 2014 census is the "before" picture for the 2020 election

2014 national share (%): 9.05
foreign_population     4.1
share_55plus          34.7
share_15_24            9.0
dtype: float64

In [52]:
# ── Stack both years and merge foreign_population + age structure into df_rdd ──

# 1. Put the two small tables under each other (each commune now appears twice: once per election cycle)
df_foreign = pd.concat([df_imm_2011, df_imm_2014], ignore_index=True)

# 2. Safety: same 5-character commune code format in df_rdd
df_rdd['code_commune'] = df_rdd['code_commune'].astype(str).str.zfill(5)

# 3. Delete old versions of the three columns, so re-running this cell does not create _x / _y duplicates
df_rdd = df_rdd.drop(columns=['foreign_population', 'share_55plus', 'share_15_24'], errors='ignore')

# 4. Merge on commune code AND election year.
#    (Merging on the code alone would duplicate rows, because each commune is in df_foreign twice.)
#    how='left' keeps every row of df_rdd; 2008 rows simply get NaN (no 2008 vintage, and 2008 is excluded anyway).
df_rdd = df_rdd.merge(df_foreign, on=['code_commune', 'election_year'], how='left')

In [53]:
df_rdd.head(3)

,code_commune,nuance,voix,election_year,tour,is_far_right,treat,d_50,skill_share_pre,skill_share_trend,delta_skill_share,pop_pre,pop_post,gender_gap_tertiary,no_diploma_share,skill_share_trend2,far_right_participated,pop_growth,income_median,income_gini,unemployment_rate,foreign_population,share_55plus,share_15_24
0,01053,LUG,437,2014,t1,False,0,-2.409639,0.392705,0.020687,0.023270,27491.52580,28388.73630,-0.010252,0.607295,0.056592,True,-0.001254,17694.500000,0.365057,17.997301,12.083779,32.183521,15.458405
1,01053,LUG,388,2020,t1,False,0,-4.088756,0.429253,0.021263,0.035516,28927.00000,29466.00000,0.001390,0.570747,NaN,True,0.032115,18276.111111,0.375722,17.078005,13.374704,32.950297,15.156634
2,02168,LDVG,335,2014,t1,False,0,-5.130327,0.345043,0.057388,-0.009702,9931.99378,10209.33112,-0.007876,0.654957,0.051668,True,0.006740,17063.666667,0.368367,22.861113,9.679392,30.633696,12.722666

## Export Final Dataframe

In [54]:
# ── 2020 cycle: replace extrapolated Cagé-Piketty outcomes with real INSEE census data ──
f = 'base-cc-diplomes-formation-2021.xlsx'
edu_cols = {'10': ['BAC', 'BACP2', 'SUP'], '15': ['BAC', 'SUP'], '21': ['BAC', 'SUP2', 'SUP34', 'SUP5']}  # bac or higher
sheets = {yy: pd.read_excel(f, sheet_name=f'COM_20{yy}', header=5, dtype={'CODGEO': str}).set_index('CODGEO')
          for yy in edu_cols}

def insee_share(yy, sex=''):
    """Share with bac or higher among non-students 15+ (sex='' all, 'F' women)."""
    d = sheets[yy]
    return sum(d[f'P{yy}_{sex}NSCOL15P_{c}'] for c in edu_cols[yy]) / d[f'P{yy}_{sex}NSCOL15P']

trend = insee_share('15') - insee_share('10')                 # pre-trend 2010 -> 2015
delta = (insee_share('21') - insee_share('15')) * 5 / 6       # post 2015 -> 2021, scaled to 5 years

m = df_rdd['election_year'] == 2020                            # overwrite ONLY the 2020 rows
df_rdd.loc[m, 'skill_share_trend'] = df_rdd.loc[m, 'code_commune'].map(trend)
df_rdd.loc[m, 'delta_skill_share'] = df_rdd.loc[m, 'code_commune'].map(delta)
print(df_rdd.loc[m, ['skill_share_trend', 'delta_skill_share']].isna().sum())   # communes not found in INSEE

skill_share_trend    0
delta_skill_share    0
dtype: int64

In [55]:
# Export clean df_rdd to CSV
df_rdd.to_csv('df_rdd_clean.csv', index=False)